version: "3.7"

networks:
  catapult-testnet-node:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16

services:
  dualnode:
    build: ./core-node/peernode
    container_name: cat-dual-node
    volumes:
      - ./core-node/config/data/:/data:rw
      - ./core-node/config/certs/:/certs:rw
      - ./core-node/config/resources:/resources
    expose:
      - 7900
      - 7902
    ports:
      - "7900:7900"
      - "7902:7902"
    networks:
      catapult-testnet-node:
        ipv4_address: 172.28.1.1

  db:
    image: mongo
    expose:
      - 27017
    ports:
      - "27017:27017"
    command: "mongod --bind_ip=db"
    networks:
      catapult-testnet-node:
        ipv4_address: 172.28.1.2
  rest:
    build: ./rest
    container_name: cat-rest-api
    expose:
      - 3000
    ports:
      - "3000:3000"
    volumes:
      - ./core-node/config/certs/:/certs
      - ./core-node/config/resources:/resources
    networks:
      catapult-testnet-node:
        ipv4_address: 172.28.1.3

  broker:
    build: ./core-node/broker
    container_name: cat-broker
    links:
      - "restore:restore"
    volumes:
      - ./core-node/config/data/:/data:rw
      - ./core-node/config/certs/:/certs
      - ./core-node/config/resources:/resources
    depends_on:
      - restore
    networks:
      catapult-testnet-node:
        ipv4_address: 172.28.1.4

  restore:
    build: ./backups/restore
    container_name: mongo-restore
    volumes:
      - ./backups/config/:/config:rw
    depends_on:
      - db
    networks:
      catapult-testnet-node:
        ipv4_address: 172.28.1.5

  store:
    build: ./backups/store
    container_name: mongo-store
    volumes:
      - ./backups/config/:/config:rw
    depends_on:
      - dualnode
      - db
      - rest
      - restore
    networks:
      catapult-testnet-node:
        ipv4_address: 172.28.1.6
